// components/SummaryModal.jsx — Modal overlay for AI summary
import React from 'react';

/**
 * Props:
 *   summary  — string, the AI-generated summary text
 *   onClose  — function, called when user closes modal
 */
function SummaryModal({ summary, onClose }) {
    // Close on overlay click
    const handleOverlayClick = (e) => {
        if (e.target === e.currentTarget) onClose();
    };

    return (
        <div className="modal-overlay" onClick={handleOverlayClick} role="dialog" aria-modal="true">
            <div className="modal-box">
                <div className="modal-header">
                    <h2 className="modal-title">
                        <span>✨</span> AI Summary
                    </h2>
                    <button className="modal-close" onClick={onClose} aria-label="Close modal">✕</button>
                </div>

                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
                    Generated by Llama 3 via Groq API
                </p>

                <div className="summary-content">
                    {summary}
                </div>

                <div style={{ marginTop: '1.25rem', display: 'flex', justifyContent: 'flex-end' }}>
                    <button className="btn btn-secondary" onClick={onClose}>Close</button>
                </div>
            </div>
        </div>
    );
}

export default SummaryModal;
